# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_homesliderimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesliderimages',
            options={'verbose_name': 'Home Image', 'verbose_name_plural': 'Home Images'},
        ),
        migrations.RenameField(
            model_name='press',
            old_name='mainImage',
            new_name='image',
        ),
    ]
